text = "hello world"
num_text = "12345"
mix_text = "Hello World 123"
spaces_text = "   python   "
title_text = "welcome to smit ai data science"
tab_text = "python\tis\tfun"
myTransTable = str.maketrans({"h": "ھ","e": "ے","l": "ل","o": "و","w": "و","r": "ر", "d": "د",})
print("1. capitalize(): ", text.capitalize())
print("2. casefold(): ", "PYTHON".casefold())
print("3. center(): ", text.center(15, "-"))
print("4. count('l'): ", text.count("l"))
print("5. encode(): ", text.encode())
print("6. endswith('ld'): ", text.endswith("ld"))
print("7. expandtabs(4): ", tab_text.expandtabs(4))
print("8. find('world'): ", text.find("world"))
print("9. format(): ", "My name is {}".format("Abdul Wahab"))
print("10. format_map(): ", "My name is {name} and I am {age} years old".format_map({"name": "Abdul Wahab", "age":"20"}))
print("11. index('world'): ", text.index("world"))
print("12. isalnum(): ", "Python3".isalnum())
print("13. isalpha(): ", "Python".isalpha())
print("14. isascii(): ", text.isascii())
print("15. isdecimal(): ", num_text.isdecimal())
print("16. isdigit(): ", num_text.isdigit())
print("17. isidentifier(): ", "Demo".isidentifier())
print("18. islower(): ", text.islower())
print("19. isnumeric(): ", num_text.isnumeric())
print("20. isprintable(): ", text.isprintable())
print("21. isspace(): ", "   ".isspace())
print("22. istitle(): ", "Hello World".istitle())
print("23. isupper(): ", "HELLO".isupper())
print("24. join(['Python','is','fun']): ", " ".join(["Python", "is", "fun"]))
print("25. ljust(20,'-'): ", text.ljust(20, "-"))
print("26. lower(): ", "HELLO".lower())
print("27. lstrip(): ", spaces_text.lstrip())
print("28. maketrans() + translate(): ", text.translate(myTransTable))
print("29. partition(' '): ", text.partition(" "))
print("30. replace('world','Python'): ", text.replace("world", "Python"))
print("31. rfind('l'): ", text.rfind("l"))
print("32. rindex('l'): ", text.rindex("l"))
print("33. rjust(20,'-'): ", text.rjust(20, "-"))
print("34. rpartition(' '): ", text.rpartition(" "))
print("35. rsplit(): ", mix_text.rsplit())
print("36. rstrip(): ", spaces_text.rstrip())
print("37. split(): ", mix_text.split())
print("38. splitlines(): ", "Hello\nWorld\nPython".splitlines())
print("39. startswith('he'): ", text.startswith("he"))
print("40. strip(): ", spaces_text.strip())
print("41. swapcase(): ", "I am Swap Case my Upper chars becomes Lower and Lower Chars becomes Upper :)".swapcase())
print("42. title(): ", title_text.title())
print("43. upper(): ", text.upper())
print("44. zfill(10): ", num_text.zfill(10))